# Generated by Django 5.0.6 on 2024-07-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_customuser_phone_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='date_joined',
            new_name='created',
        ),
    ]
